language: scala

jdk: oraclejdk8

scala:
  - 2.11.11

script:
  - sbt test

notifications:
  email: false

sudo: false

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  bundler: true
  directories:
    - $HOME/.sbt/launchers/
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.coursier
